# Use the official Apache image as the base image
FROM httpd:latest

# Copy your Apache configuration (if needed)
# COPY ./my-apache-config.conf /usr/local/apache2/conf/httpd.conf

# Expose port 8081
EXPOSE 8081
